services:
  - type: web
    name: rutinas
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-rutinas.onrender.com:3306/rutinas_db
      - key: SPRING_DATASOURCE_USERNAME
        value: user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 1234
    ports:
      - 9090

  - type: web
    name: mysql-rutinas
    env: docker
    dockerfilePath: mysql.Dockerfile
    plan: free
    autoDeploy: false
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: 1234
      - key: MYSQL_DATABASE
        value: rutinas_db
      - key: MYSQL_USER
        value: user
      - key: MYSQL_PASSWORD
        value: 1234
    ports:
      - "3306"
